### ISSUE TITLE
CONFIG.BBS

### ISSUE THREAD

**Issue by sikofitt** [M-griffin/Oblivion2-XRM#1]
Can you add an example of CONFIG.BBS?  xrm-server doesn't seem to want to create the file on Ubuntu 14.04 LTS.

**Comment by M-griffin** [comment]
Hi Sikofitt,  thanks for your interest.  Right now the CONFIG.BBS is only a temp file from the original Oblivion/2 package to help in reading / translating the original data file sets.  Currently this system is still in very early development and doesn't really do much other then accept connections and display a simple menu.  

All functionally is still very much a WIP.  If you still interested from a development standpoint I can put a data file archive together because it also needs Menu's and ANSI screens.  And I'm also in the progressing of rewriting to use SQLite and migrating the original data files at this time.  So lots of changes to come.

**Comment by M-griffin** [comment]
Work has slowly started again, CONFIG.BBS references have been removed for new xrm-config.xml file which is auto generated on the first run.  Folder for test screens and menu will have to be added next.
